# Generated by Django 2.1 on 2018-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_level_clears'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='cars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
