# Generated by Django 2.1 on 2018-08-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20180823_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='clears',
        ),
    ]
