# Generated by Django 2.1 on 2018-08-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_remove_level_clears'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='number',
        ),
    ]
