# Generated by Django 2.1 on 2018-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0010_remove_level_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
