# Generated by Django 2.1 on 2018-09-24 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0012_auto_20180823_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='clear',
            name='moves',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clear',
            name='succesful',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clear',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
