# Generated by Django 2.1 on 2018-09-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0013_auto_20180924_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clear',
            old_name='succesful',
            new_name='successful',
        ),
    ]
